ReactDOMRe.renderToElementWithId
  <div>
    <Image
      source="https://fakeimg.pl/400x450/?retina=true"
      resizeMode=Cover
      width=100
      height=100
      backgroundColor="#ccc"
    />
    <br />
    <Image
      source="https://fakeimg.pl/200x300/?retina=true"
      resizeMode=Contain
      width=300
      height=300
      backgroundColor="#000"
      round=true
    />
  </div>
  "root";
